// Generated by CoffeeScript 1.10.0
(function() {
  var i, j, len, mixr, parentDivForMixr, yamiColorArray;

  yamiColorArray = ["#1abqc", "#2ecc71", "#3498db", "#9b59b6", "#34495e", "#16a085", "#27ae60"];


  /*
      Given a parent div, iterate through its children, and apply colors from yamiColorArray at interval i.
   */

  parentDivForMixr = document.getElementsByClassName();

  if (parentDivForMixr.length >= 1) {
    for (j = 0, len = parentDivForMixr.length; j < len; j++) {
      i = parentDivForMixr[j];
      console.log(i);
    }
  }


  /*
      Mixr function: Iterate through child divs and add a background-color of a
   */

  mixr = function(children) {
    var k, len1, results;
    results = [];
    for (k = 0, len1 = children.length; k < len1; k++) {
      i = children[k];
      results.push(console.log(i));
    }
    return results;
  };

}).call(this);
